### PR TITLE
[Yiounah]markdown file about preferred lectures

### PR DESCRIPTION
**Pull request by Yiounah**
Hi, @mmcky !
  Sorry for being late, it is the first try of PR about a list of lectures I want to review.

Best,
Yuna

### CODE REVIEW

**Comment by Yiounah** [comment]
On Friday, when I tried to git clone, I met proxy problem. I don't know the details, but when I make the port number of the local system consistent with the port number of git, it works.
proxy problem

**Comment by mmcky** [comment]
thanks @Yiounah.

**Comment by mmcky** [comment]
@HumphreyYang this is something we could add to our manual?

**Comment by HumphreyYang** [comment]
> @HumphreyYang this is something we could add to our manual?

Thanks @mmcky and @Yiounah, I think this is related to the local firewall/DNS setting. Would you think it is helpful to add?

**Comment by mmcky** [comment]
thanks @HumphreyYang -- ah if this is just an individual computer issue. No need. I had read it as a broader issue for RAs in china accessing github.

**Comment by HumphreyYang** [comment]
> thanks @HumphreyYang -- ah if this is just an individual computer issue. No need. I had read it as a broader issue for RAs in china accessing github.

Hi @mmcky, I think it might worth noting to other RAs as it might relate to XMU's internet setting : )

**Comment by JunnanZ** [comment]
I think what Yuna did was configure git to use a VPN set up on port 7890 (this is the port number `clash` uses). So this only works if you already have a VPN.

In general, people can access github in China, although sometimes the connection can be slow or unreliable.

**Pull request merged**
